### ISSUE TITLE
bundlesize.ci from GitHub auth request doesn't resolve

### ISSUE THREAD

**Issue by kumar303** [siddharthkp/bundlesize#43]
When bundlesize requests read/write access via GitHub, the application metadata lists https://bundlesize.ci which does not resolve. Maybe that link needs to be updated?

**Comment by siddharthkp** [comment]
Fixed that!

**Comment by kumar303** [comment]
https://bundlesize.ci/ still doesn't resolve for me. What was the fix?

**Comment by siddharthkp** [comment]
`https://bundlesize.ci` doesn't really exist

Changed the url to the project on github :P
